name: Node.js CI

on: [push, pull_request]
jobs:
  build:
    name: Frontend Build
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
    
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          working-directory: frontend
      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            echo "yarn.lock file not found"
            exit 1
          fi
      - name: Build
        run: yarn build